FROM node:20

WORKDIR /usr/src/project/apps/

COPY package.json pnpm-lock.yaml ./

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install

COPY . .

RUN pnpm run migrate:db
RUN pnpm run build

EXPOSE 3002

CMD ["pnpm", "run", "start:frontend"]
