FROM node:20  

WORKDIR /usr/src/project  

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./  
COPY ./apps/http-backend ./apps/http-backend  
COPY ./packages ./packages  

RUN corepack enable && corepack prepare pnpm@latest --activate  
RUN pnpm install  

WORKDIR /usr/src/project/packages/db  
RUN pnpm exec prisma generate  

WORKDIR /usr/src/project/apps/http-backend  
RUN pnpm run build  

WORKDIR /usr/src/project  

EXPOSE 3000  
CMD ["pnpm", "run", "start:backend"]
