FROM node:20 AS builder

WORKDIR /usr/src/project

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY ./apps/frontend ./apps/frontend
COPY ./packages ./packages

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install

WORKDIR /usr/src/project/packages/db
RUN pnpm exec prisma generate
RUN pnpm exec prisma migrate deploy

WORKDIR /usr/src/project/apps/frontend
RUN pnpm run build

WORKDIR /usr/src/project

EXPOSE 3002

CMD ["pnpm", "run", "start:frontend"]
