FROM node:20 AS builder

WORKDIR /usr/src/project

COPY package.json pnpm-lock.yaml ./
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run migrate:db
RUN pnpm run build

# Production Image
FROM node:20

WORKDIR /usr/src/project
COPY --from=builder /usr/src/project ./

ENV DATABASE_URL={$DATABASE_URL}

EXPOSE 3002
CMD ["pnpm", "run", "start:frontend"]
